version: '3.9'
services:
  nats:
    image: nats:2.7.4
    ports:
      - "4222:4222"
      - "8222:8222"
      - "6222:6222"
    healthcheck:
      test: [ "CMD-SHELL", "curl nats:8222" ]
      interval: 5s
      timeout: 5s
      retries: 5
