version: '3.9'
services:
  patient-group-postgres:
    image: postgres:14.2
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-test}
      POSTGRES_DB: "patientGroup"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-test} -d patientGroup"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  patient-group-service:
    depends_on:
      patient-group-postgres:
        condition: service_healthy
      nats:
        condition: service_started
    build:
      context: .
      dockerfile: Patient-Group-Service/Dockerfile
    ports:
      - "5050:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Staging

# join swsp
networks:
  default:
    name: swsp
